"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var cliente_1 = require("./Examen2/cliente");
var compresion_1 = require("./Examen2/compresion");
var documento_1 = require("./Examen2/documento");
var encriptacion_1 = require("./Examen2/encriptacion");
var objFormaComprimir = new compresion_1.default();
var objFormaEncriptar = new encriptacion_1.default();
var documento = new documento_1.default("unarchivo", "el contenido del archivo");
var objCliente = new cliente_1.default(documento, objFormaComprimir);
console.log(objCliente.mostrarInformacionDelDocumento());
objCliente.procesarArchivo();
console.log(objCliente.mostrarInformacionDelDocumento());
objCliente.cambiarForma(objFormaEncriptar);
objCliente.procesarArchivo();
console.log(objCliente.mostrarInformacionDelDocumento());
